mode: train
train:
  dataset: MvRgbDatasetAvatarReX
  data:
    map_size: 512
    subject_name: avatarrex_lbn1
    data_dir: ../avatarrex/lbn1
    frame_range: &id001
    - 0
    - 1901
    - 1
    used_cam_ids: [0, 1, 2, 3, 4, 5, 6, 8, 9, 10, 11, 12, 14, 15]
    load_smpl_pos_map: true
  pretrained_dir: null
  net_ckpt_dir: ./results/avatarrex_lbn1/avatar
  prev_ckpt: null
  ckpt_interval:
    epoch: 1
    batch: 5000
  eval_interval: 100
  eval_training_ids: [481, 0]
  eval_testing_ids: [507, 8]
  eval_img_factor: 1.0
  pretrain_iters: 5_000
  train_iters: 45_000
  lr_init: 0.0005
  loss_weight:
    l1: 1.0
    lpips: 0.1
    mask: 0.1
    depth: 0.1
    predicted_depth: 0.1
    offset: 0.005
    opacity: 0.1
    opacity_symmetric: 0.003
    scale: 0.01
    skinning_weight: 0.1
  finetune_color: false
  batch_size: 1
  num_workers: 8
  random_bg_color: true

  # densification configs
  densification_interval: 100
  densify_from_iter: 0
  densify_until_iter: 200_000
  densify_grad_threshold: 0.0002
  opacity_threshold: 0.05
  camera_extent: 3.469298553466797

test:
  dataset: MvRgbDatasetAvatarReX
  data:
    data_dir: ../avatarrex/lbn1
    frame_range: *id001
    subject_name: avatarrex_lbn1
  pose_data:
#    data_path: Z:/Data/Pose/thuman4/pose_00.npz
#    frame_range: [2000, 2500]
#    data_path: Z:/Data/Pose/AMASS/CMU/06/06_13_poses.npz
    data_path: Z:/Data/Pose/AMASS/CMU/10/10_05_poses.npz
    frame_interval: 4
  view_setting: moving
  render_view_idx: 18
  global_orient: true
  img_scale: 1.0
  save_mesh: false
  render_skeleton: false
  save_tex_map: false
  save_ply: false
  fix_hand: true
  fix_hand_id: 55
  n_pca: 20
  sigma_pca: 2.0
  prev_ckpt: ./results/avatarrex_lbn1/avatar/batch_800000
model:
  with_viewdirs: true
  random_style: false
  lbs_weights: lbs_weights
  lbs_weight_interpolation: linear

  mlp:
    n_neurons: 64
    n_hidden_layers: 2
    skip_in: []
    cond_in: []
    multires: 0

  feat_dim: 32

  gaussian:
    position_lr_init: 0.00016
    position_lr_final: 0.0000016
    position_lr_delay_mult: 0.01
    #TODO
    position_lr_max_steps: 200_000
    feature_lr: 0.0025
    opacity_lr: 0.05
    scaling_lr: 0.005
    rotation_lr: 0.001
    percent_dense: 0.01
    # TODO
    uv_spatial_lr: 0.1
